title: "Threat Intelligence Reports"
description: "Cyber Threat Intelligence Research & Investigations"
url: "https://sw4pn33.github.io"
baseurl: "/threat-intel"
permalink: /blog/:title/

author:
  name: "Sw4pn33"
  role: "Threat Intelligence Researcher"
  github: "https://github.com/Sw4pn33"
  linkedin: "https://www.linkedin.com/in/swopna-sarit-barik-75a9a9278/"

markdown: kramdown
highlighter: rouge

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
